### ISSUE TITLE
Recommendation: Wrong way for managing required configurations

### ISSUE THREAD

**Issue by ramin-guliyev** [beyrakIn/mesmerizer#1]
Configurations in code is a bad practices for user friendly tools. 
Building application each time is a suffer for the user. 
Recommendation: Use any config file for managing configurations and please publish release. 

Btw awesome tool, thank you for open-source contribution

**Comment by beyrakIn** [comment]
It nifty trick, actually I did not build the app because of this, I will fix this ASAP. Thank you!
